<a href="https://colab.research.google.com/github/Shahbaz894/meachine-learning-/blob/main/NumpyTipsandTricksByCampus_X.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

np.sort
returen a sorted array

In [ ]:
 # code
import numpy as np
a = np.random.randint(1,100,15)
a

array([72, 28, 14, 87, 33, 98, 57, 89, 83, 80, 42, 93, 90, 43, 71])

In [ ]:
np.sort(a)[::-1]

array([98, 93, 90, 89, 87, 83, 80, 72, 71, 57, 43, 42, 33, 28, 14])

In [ ]:
np.sort(a)

array([14, 28, 33, 42, 43, 57, 71, 72, 80, 83, 87, 89, 90, 93, 98])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)

np.sort(b,axis=0)

array([[ 1, 19, 10,  6],
       [56, 45, 15,  7],
       [78, 49, 32, 44],
       [80, 56, 36, 48],
       [85, 76, 64, 51],
       [89, 89, 90, 86]])

## np.append
The numpy.append() appends values along the mentioned axis at the end of the array

In [ ]:
np.append(a,200)

array([ 72,  28,  14,  87,  33,  98,  57,  89,  83,  80,  42,  93,  90,
        43,  71, 200])

In [ ]:
b=np.append(b,np.ones((b.shape[0],1)),axis=1)
b

array([[89., 56., 10., 48.,  1.,  1.],
       [56., 76., 90.,  6.,  1.,  1.],
       [ 1., 45., 15., 51.,  1.,  1.],
       [80., 89., 36.,  7.,  1.,  1.],
       [85., 19., 64., 86.,  1.,  1.],
       [78., 49., 32., 44.,  1.,  1.]])

In [ ]:
c=np.arange(24).reshape(4,6)

c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

## np.concatenate
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [ ]:
a=np.arange(20).reshape(4,5)
b=np.arange(20).reshape(4,5)
print(a)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## np.unique
With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# Expand Dimension
With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

In [ ]:
# code
a.shape

(4, 5)

In [ ]:
np.expand_dims(a,axis=1).shape

(4, 1, 5)

In [ ]:
a.shape

(4, 5)

In [ ]:
np.expand_dims(a,axis=0).shape

(1, 4, 5)

## np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [ ]:
a=np.arange(180)

In [ ]:
# find all indices with value greater than 50

np.where(a>50)

(array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
        116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
        142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
        155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179]),)

In [ ]:
# replace all values > 50 with 0
#np.where(condition,true,false)
np.where(a>50,0,a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

## np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [ ]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179])

In [ ]:
np.argmax(a)

179

In [ ]:
b=np.random.randint(1,100,50)
b

array([95, 52, 35, 47, 13, 55, 76,  6,  9, 28, 10,  8, 55, 39, 50,  3, 54,
       55, 25, 50, 59, 99, 58, 23,  6, 61, 19, 93, 61, 78, 48, 63, 61, 52,
        8, 92, 10, 87, 63, 27,  9, 73, 45, 16, 50, 82, 76, 32, 88, 76])

In [ ]:
np.argmax(b)

21

In [ ]:
np.argmin(b)

15

## np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [ ]:
b

array([95, 52, 35, 47, 13, 55, 76,  6,  9, 28, 10,  8, 55, 39, 50,  3, 54,
       55, 25, 50, 59, 99, 58, 23,  6, 61, 19, 93, 61, 78, 48, 63, 61, 52,
        8, 92, 10, 87, 63, 27,  9, 73, 45, 16, 50, 82, 76, 32, 88, 76])

In [ ]:
np.cumsum(b)

array([  95,  147,  182,  229,  242,  297,  373,  379,  388,  416,  426,
        434,  489,  528,  578,  581,  635,  690,  715,  765,  824,  923,
        981, 1004, 1010, 1071, 1090, 1183, 1244, 1322, 1370, 1433, 1494,
       1546, 1554, 1646, 1656, 1743, 1806, 1833, 1842, 1915, 1960, 1976,
       2026, 2108, 2184, 2216, 2304, 2380])

In [ ]:
c=np.arange(24).reshape(4,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
np.cumsum(c,axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  8, 10, 12, 14, 16],
       [18, 21, 24, 27, 30, 33],
       [36, 40, 44, 48, 52, 56]])

## np.percentile
numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

In [ ]:
b


array([95, 52, 35, 47, 13, 55, 76,  6,  9, 28, 10,  8, 55, 39, 50,  3, 54,
       55, 25, 50, 59, 99, 58, 23,  6, 61, 19, 93, 61, 78, 48, 63, 61, 52,
        8, 92, 10, 87, 63, 27,  9, 73, 45, 16, 50, 82, 76, 32, 88, 76])